import { createRequire } from "node:module";
import assert from "node:assert/strict";
import {preparePwa,preparePwaPage,pwaOptions} from './pwa-qa-context.mjs';
const require = createRequire(import.meta.url);
const { chromium, webkit } = require(process.env.PLAYWRIGHT_MODULE || "playwright");
const engine = process.env.NAV_ENGINE || 'chromium';
const browser = await (engine === 'webkit' ? webkit : chromium).launch({ headless: true, ...(engine === 'chromium' && process.env.PLAYWRIGHT_CHANNEL ? { channel: process.env.PLAYWRIGHT_CHANNEL } : {}) });
const context = await browser.newContext({ viewport: { width: 390, height: 844 }, ...pwaOptions(390), serviceWorkers: "block" });
await preparePwa(context,390);
await context.addInitScript(() => {
  if (localStorage.getItem("calorie-counter-state")) return;
  localStorage.setItem("calorie-counter-state", JSON.stringify({
    user: { name: "Navigation QA", sex: "male", age: 30, heightCm: 180, weightKg: 75, targetWeightKg: 70, goalType: "lose", activityMultiplier: 1.375, weeklyRateKg: 0.5 },
    goals: { calories: 2000, protein: 140, carbs: 240, fat: 60 }, progress: [], days: {}, theme: "light",
  }));
});
const page = await context.newPage();
if (engine === 'chromium') await preparePwaPage(page);
page.setDefaultTimeout(10000);
const errors = [];
let documents = 0;
page.on("pageerror", error => errors.push(error.message));
page.on("request", request => { if (request.isNavigationRequest()) documents++; });
try {
  const entry = new URL(process.env.INTAKE_URL || "http://127.0.0.2:3001/index.html");
  await page.goto(new URL('/privacy.html', entry).href);
  await page.goto(new URL('/index.html', entry).href);
  await page.locator(".day-tile").first().waitFor();
  const rootHistoryLength = await page.evaluate(() => history.length);
  const initialDocuments = documents;
  await page.evaluate(() => { window.qaFooter = document.querySelector(".mobile-tabbar"); window.qaShell = document.querySelector(".app-shell"); });
  const nav = page.getByRole("navigation", { name: "Mobile navigation", exact: true });
  const samples = [];
  async function tab(name, selector) {
    const start = Date.now();
    await nav.getByRole("link", { name, exact: true }).click();
    await page.locator(selector).waitFor({ state: "visible" });
    samples.push({ name, milliseconds: Date.now() - start });
    assert.equal(await page.evaluate(() => window.qaFooter === document.querySelector(".mobile-tabbar") && window.qaShell === document.querySelector(".app-shell")), true);
  }
  for (let i = 0; i < 3; i++) {
    await tab("Progress", "#progressChart");
    await tab("Assistant", "#assistantInput");
    await tab("Profile", "#profileSettingsOverview");
    await tab("Today", "#calendarStrip");
  }
  await tab("Assistant", "#assistantInput");
  await page.locator("#assistantInput").fill("Keep this draft");
  await tab("Progress", "#progressChart");
  await tab("Assistant", "#assistantInput");
  assert.equal(await page.locator("#assistantInput").inputValue(), "Keep this draft");
  assert.equal(await page.evaluate(() => history.length), rootHistoryLength, 'bottom tabs must replace their current history entry');
  assert.equal(documents, initialDocuments, 'bottom-tab switches must stay in one document');
  await page.goBack();
  assert.match(page.url(), /privacy\.html$/, 'Back must leave the root-tab entry, not reveal Progress');
  await page.goForward();
  await page.locator("#assistantInput").waitFor({ state: "visible" });
  await page.evaluate(() => { window.qaFooter = document.querySelector('.mobile-tabbar'); window.qaShell = document.querySelector('.app-shell'); });
  const documentsAfterHistory = documents;
  await page.locator('#assistantHistoryOpen').click();
  assert.ok(await page.evaluate(() => history.state?.intakeAssistantSurface), 'Assistant History owns a real child entry');
  await page.goBack();
  await page.locator('#assistantHistory').waitFor({ state: 'hidden' });
  assert.match(page.url(), /assistant\.html$/);
  await tab("Profile", "#profileSettingsOverview");
  const profileHistoryLength = await page.evaluate(() => history.length);
  await tab('Profile', '#profileSettingsOverview');
  assert.equal(await page.evaluate(() => history.length), profileHistoryLength, 'tapping the selected tab must not add history');
  await page.locator('[data-edit-settings=plan]').click();
  assert.ok(await page.evaluate(() => history.state?.intakeNestedPage), 'Edit plan owns a real child entry');
  await page.goBack();
  await page.locator('#profileSettings[data-profile-view=summary]').waitFor();
  assert.match(page.url(), /profile\.html$/);
  await page.locator('#profilePrivacyOpen').click();
  assert.ok(await page.evaluate(() => history.state?.intakeNestedPage), 'Data & privacy owns a real child entry');
  await page.goBack();
  await page.locator('#profileDataScreen').waitFor({ state: 'hidden' });
  await page.locator('[data-edit-settings=personal]').click();
  await page.getByRole("textbox", { name: "Name (optional)", exact: true }).fill("Unsaved draft");
  await page.evaluate(()=>window.IntakeNavigate('index.html'));
  assert.match(page.url(), /profile.html/);
  assert.equal(await page.locator('#profileForm').isVisible(), true);
  assert.equal(await page.locator('#profileName').inputValue(),'Unsaved draft');
  assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('calorie-counter-state')).user.name), 'Navigation QA');
  await page.locator('#profileCancelButton').click();await page.locator('#profileSettings[data-profile-view=summary]').waitFor();
  await tab("Today", "#calendarStrip");
  await tab("Profile", "#profileSettingsOverview");
  await page.locator('[data-edit-settings=plan]').click();
  await page.getByRole("textbox", { name: "Current weight (kg)", exact: true }).fill("76");
  await page.getByRole("button", { name: "Save changes", exact: true }).click();
  await page.locator('#profileSettings[data-profile-view=summary]').waitFor();
  await tab("Today", "#calendarStrip");
  await page.locator("#calendarStrip").waitFor({ state: "visible" });
  assert.equal(await page.locator('.mobile-diary-stats').count(),0);
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('calorie-counter-state')).user.weightKg),76);
  assert.equal(Number(await page.locator('#goalCaloriesText').textContent()),await page.evaluate(()=>JSON.parse(localStorage.getItem('calorie-counter-state')).goals.calories),'updated plan still reaches Today');
  await page.locator('#floatingAddButton').click();
  await page.locator('#foodScanButton').click();
  await page.locator('.unified-scanner[open]').waitFor();
  assert.ok(await page.evaluate(() => history.state?.intakeScanner), 'Scan food owns a real child entry');
  await page.goBack();
  await page.locator('.unified-scanner').waitFor({ state: 'detached' });
  assert.equal(await page.locator('#foodSection.is-adding').count(), 1, 'scanner Back returns to Add');
  await page.locator('#closeFoodModal').click();
  await page.locator('.add-flow-host').waitFor({ state: 'detached' });
  assert.equal(await page.locator('#calendarStrip').isVisible(), true, 'Add Back returns to Today');
  const beforeRapidHistory = await page.evaluate(() => history.length);
  await page.evaluate(() => Promise.all([window.IntakeNavigate("progress.html"), window.IntakeNavigate("assistant.html")]));
  await page.locator("#assistantInput").waitFor({ state: "visible" });
  assert.equal(await page.locator('.mobile-tabbar [aria-current=page]').getAttribute('href'), 'assistant.html');
  assert.equal(await page.evaluate(() => history.length), beforeRapidHistory, 'rapid tab switches must not append history');
  await context.setOffline(true);
  await tab("Today", "#calendarStrip");
  await tab("Progress", "#progressChart");
  await tab("Assistant", "#assistantInput");
  await tab("Profile", "#profileSettingsOverview");
  await context.setOffline(false);
  assert.equal(documents, documentsAfterHistory, "tab switching must not perform document navigation");
  assert.equal(await page.locator('.mobile-tabbar [aria-current=page]').getAttribute('href'), 'profile.html');
  await page.reload();
  await page.locator('#profileSettingsOverview').waitFor();
  assert.equal(await page.locator('.mobile-tabbar [aria-current=page]').getAttribute('href'), 'profile.html', 'reload restores selected destination');
  const deepLink = await context.newPage();
  await deepLink.goto(new URL('/progress.html', entry).href);
  await deepLink.locator('#progressChart').waitFor();
  assert.equal(await deepLink.locator('.mobile-tabbar [aria-current=page]').getAttribute('href'), 'progress.html', 'deep link selects Progress');
  await deepLink.close();
  assert.deepEqual(errors, []);
  console.log(JSON.stringify({ engine, documents, errors, samples, checks: "repeated root replacements, selected-tab no-op, persistent footer/shell, draft, root Back bypass, Assistant/Profile/scanner child Back, unsaved-profile guard, profile save, rapid navigation, warm offline tabs, reload and deep link" }, null, 2));
} catch (error) {
  console.error(JSON.stringify({ url: page.url(), errors, body: await page.locator("body").innerText() }));
  throw error;
} finally { await browser.close(); }
